#!/bin/bash
# First, purge all .pyc files to clean the source tree,
# in case some modules were deleted or removed.

find . -name "*.pyc" -delete

nosetests eqcatalogue/ --with-doctest `find qa_tests/ -name 'test_*.py'`
