#!/bin/bash
# First, purge all .pyc files to clean the source tree,
# in case some modules were deleted or removed.

find . -name "*.pyc" -delete

nosetests eqcatalogue/ --with-doctest `find tests/ -name 'test_*.py'` --with-coverage --cover-package=eqcatalogue --with-xunit --xunit-file='nosetests.xml' --nologcapture
