# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_dock.ui'
#
# Created: Thu Jul 11 13:20:29 2013
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Dock(object):
    def setupUi(self, Dock):
        Dock.setObjectName(_fromUtf8("Dock"))
        Dock.resize(318, 689)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/inasafe/icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dock.setWindowIcon(icon)
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.verticalLayout = QtGui.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout.setContentsMargins(3, 0, 3, 3)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.dbGrb = QtGui.QGroupBox(self.dockWidgetContents)
        self.dbGrb.setObjectName(_fromUtf8("dbGrb"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.dbGrb)
        self.verticalLayout_2.setContentsMargins(0, 6, 0, 0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 10, -1, -1)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.selectDbComboBox = QtGui.QComboBox(self.dbGrb)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectDbComboBox.sizePolicy().hasHeightForWidth())
        self.selectDbComboBox.setSizePolicy(sizePolicy)
        self.selectDbComboBox.setObjectName(_fromUtf8("selectDbComboBox"))
        self.horizontalLayout_3.addWidget(self.selectDbComboBox)
        self.addDbBtn = QtGui.QToolButton(self.dbGrb)
        self.addDbBtn.setObjectName(_fromUtf8("addDbBtn"))
        self.horizontalLayout_3.addWidget(self.addDbBtn)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.verticalLayout.addWidget(self.dbGrb)
        self.magnitudeGrb = QtGui.QGroupBox(self.dockWidgetContents)
        self.magnitudeGrb.setObjectName(_fromUtf8("magnitudeGrb"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.magnitudeGrb)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.mag_range = DoubleRangeFilter(self.magnitudeGrb)
        self.mag_range.setObjectName(_fromUtf8("mag_range"))
        self.verticalLayout_4.addWidget(self.mag_range)
        self.verticalLayout.addWidget(self.magnitudeGrb)
        self.timeGrb = QtGui.QGroupBox(self.dockWidgetContents)
        self.timeGrb.setObjectName(_fromUtf8("timeGrb"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.timeGrb)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_2 = QtGui.QLabel(self.timeGrb)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_2)
        self.maxDateDe = QtGui.QDateTimeEdit(self.timeGrb)
        self.maxDateDe.setCalendarPopup(True)
        self.maxDateDe.setObjectName(_fromUtf8("maxDateDe"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.maxDateDe)
        self.minDateDe = QtGui.QDateTimeEdit(self.timeGrb)
        self.minDateDe.setCalendarPopup(True)
        self.minDateDe.setObjectName(_fromUtf8("minDateDe"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.minDateDe)
        self.label_3 = QtGui.QLabel(self.timeGrb)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_3)
        self.verticalLayout_3.addLayout(self.formLayout)
        self.verticalLayout.addWidget(self.timeGrb)
        self.actionsBtns = QtGui.QVBoxLayout()
        self.actionsBtns.setContentsMargins(-1, 0, -1, -1)
        self.actionsBtns.setObjectName(_fromUtf8("actionsBtns"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.drawBtn = QtGui.QPushButton(self.dockWidgetContents)
        self.drawBtn.setObjectName(_fromUtf8("drawBtn"))
        self.horizontalLayout.addWidget(self.drawBtn)
        self.clearBtn = QtGui.QPushButton(self.dockWidgetContents)
        self.clearBtn.setObjectName(_fromUtf8("clearBtn"))
        self.horizontalLayout.addWidget(self.clearBtn)
        self.actionsBtns.addLayout(self.horizontalLayout)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.filterBtn = QtGui.QPushButton(self.dockWidgetContents)
        self.filterBtn.setEnabled(True)
        self.filterBtn.setObjectName(_fromUtf8("filterBtn"))
        self.horizontalLayout_4.addWidget(self.filterBtn)
        self.downloadBtn = QtGui.QPushButton(self.dockWidgetContents)
        self.downloadBtn.setEnabled(False)
        self.downloadBtn.setObjectName(_fromUtf8("downloadBtn"))
        self.horizontalLayout_4.addWidget(self.downloadBtn)
        self.actionsBtns.addLayout(self.horizontalLayout_4)
        self.verticalLayout.addLayout(self.actionsBtns)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        Dock.setWidget(self.dockWidgetContents)

        self.retranslateUi(Dock)
        QtCore.QMetaObject.connectSlotsByName(Dock)

    def retranslateUi(self, Dock):
        Dock.setWindowTitle(QtGui.QApplication.translate("Dock", "Events Catalogue", None, QtGui.QApplication.UnicodeUTF8))
        self.dbGrb.setTitle(QtGui.QApplication.translate("Dock", "Select one of the availables db", None, QtGui.QApplication.UnicodeUTF8))
        self.addDbBtn.setText(QtGui.QApplication.translate("Dock", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.magnitudeGrb.setTitle(QtGui.QApplication.translate("Dock", "Define magnitude range", None, QtGui.QApplication.UnicodeUTF8))
        self.timeGrb.setTitle(QtGui.QApplication.translate("Dock", "Define time range", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dock", "From", None, QtGui.QApplication.UnicodeUTF8))
        self.maxDateDe.setDisplayFormat(QtGui.QApplication.translate("Dock", "dd.MM.yyyy hh:mm:ss", None, QtGui.QApplication.UnicodeUTF8))
        self.minDateDe.setDisplayFormat(QtGui.QApplication.translate("Dock", "dd.MM.yyyy hh:mm:ss", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dock", "To", None, QtGui.QApplication.UnicodeUTF8))
        self.drawBtn.setText(QtGui.QApplication.translate("Dock", "Draw", None, QtGui.QApplication.UnicodeUTF8))
        self.clearBtn.setText(QtGui.QApplication.translate("Dock", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.filterBtn.setText(QtGui.QApplication.translate("Dock", "Filter", None, QtGui.QApplication.UnicodeUTF8))
        self.downloadBtn.setText(QtGui.QApplication.translate("Dock", "Download", None, QtGui.QApplication.UnicodeUTF8))

from rangeFilter import DoubleRangeFilter
import resources_rc
